### ISSUE TITLE
Marks U+1E4EE and U+1E4EF are not centered

### ISSUE THREAD

**Issue by dscorbett** [notofonts/nag-mundari#2]
### Font
NotoSansNagMundari-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/nag-mundari/releases/tag/NotoSansNagMundari-v1.000
Date: 2023-03-16

### Font version
Version 1.000

### Issue
U+1E4EE NAG MUNDARI SIGN IKIR and U+1E4EF NAG MUNDARI SIGN SUTUH are not centered below and above base glyphs, including letters and the dotted circle. See [L2/21-031R](https://www.unicode.org/L2/L2021/21031r-mundari.pdf) figures 9 and 11 for examples.

### Character data
◌𞓮𞓯𞓕𞓮𞓜𞓯
U+25CC DOTTED CIRCLE
U+1E4EE NAG MUNDARI SIGN IKIR
U+1E4EF NAG MUNDARI SIGN SUTUH
U+1E4D5 NAG MUNDARI LETTER A
U+1E4EE NAG MUNDARI SIGN IKIR
U+1E4DC NAG MUNDARI LETTER IDD
U+1E4EF NAG MUNDARI SIGN SUTUH

### Screenshot
![◌𞓮𞓯𞓕𞓮𞓜𞓯](https://user-images.githubusercontent.com/1124347/225732246-f3f9e71d-8691-4a88-9a5f-f59aa19d78f0.png)

**Comment by lwolfsonkin** [comment]
Hello! Author of the Mundari Bani/Nag Mundari proposal here! Indeed, I was about to reach out about this as I noticed this on my computer as well, but seems David Corbett just beat me! :) IKIR and SUTUH should be centered on the base character. The other two marks (MUHOR and TOYOR) are off to the right (as you've currently done correctly). Thank you for creating this!

**Comment by Mercury13** [comment]
Here’s my Nag. Made for Unicodia, but completely working, not just a bunch of glyphs. Of course, not variable at all.
![изображение](https://user-images.githubusercontent.com/10164882/225979896-37ca28d4-c213-4dc5-bbb7-c45a2c49a760.png)
Three anchors. Spacing prime. Prime is mostly put right using kerning, but because of thin advance width I made six RLIGs, otherwise letters are put too closely.

**Comment by Mercury13** [comment]
@lwolfsonkin , Is my font right?

**Comment by simoncozens** [comment]
This is a problem with the toolchain; the font source is right. I'll take a look.
